Fix os-downstream-tag.py downstream tag matching
If the most recent downstream tag is not patching the most recent
upstream tag, but there is another downstream tag that is patching the
most recent upstream tag, the next downstream tag would be chosen
incorrectly.

This is best shown with an example.

Run naming-things-is-hard/os-downstream-tag.py --release $(basename $(git rev-parse --abbrev-ref HEAD))
Fetching from origin
Fetching from stackhpc
Found downstream tag stackhpc/10.0.0.13
Merge base of 661f7c9fcef554deb7765fb4300ef045ef3d50a5 and 422be9f0d581d9caa0d161b6c54c90147feb7e4f is b'661f7c9fcef554deb7765fb4300ef045ef3d50a5'
Most recent upstream tag: 11.1.0
Error: stackhpc/11.1.0.1 already exists as an unreachable tag, please delete and retry
Error: Process completed with exit code 1.

The problem here is that it thinks that the most recent tag is
stackhpc/10.0.0.13, but actually there is stackhpc/11.1.0.3.

We have the wallaby tag stackhpc/10.0.0.13 in the commit history due to
merging stackhpc/wallaby into stackhpc/xena. This is not something we
typically do with OpenStack repositories, where the stable branches
diverge, however with kayobe-config it sometimes makes sense to do so.

This change fixes the issue by filtering the considered downstream tags
based on the most recent upstream tag.